on:
  pull_request:
    branches:
      - master

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.affected_services.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run script
        id: affected_services
        run: |
          OUTPUT=$(python main.py)
          echo "services=$OUTPUT" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    if: needs.detect.outputs.services != '[]'
    needs: detect
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          cd services/${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          pip install pytest
          pytest -v
  build:
    runs-on: ubuntu-latest
    if: needs.detect.outputs.services != '[]'
    needs: [detect, test]
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Image Tag
        id: vars
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: services/${{ matrix.service }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:${{ steps.vars.outputs.tag }}
